French Translation
73VW/Publishing-to-PyPI-with-pbr-and-Travis pull request #22
Opened 2019-10-17 18:03 UTC by Ectalite

Created the French translation and fixed a typo

2020-02-12 18:46 UTC, 73VW requested changes
Merci pour le boulot mais il y a encore passablement de fautes d'orthographe. Je ne vais pas merger pour le moment.

2020-02-12 18:46 UTC, 73VW commented on README.fr.rst
> +    # Où est le commencement de votre application?
J'aurais plutôt tendance à commenter un truc du genre "Quel fichier est le point d'entrée de votre application?"

2020-10-02 17:07 UTC, Ectalite commented on README.fr.rst
> +    # Où est le commencement de votre application?
Ce serait la seule chose a modifier ?

2020-10-03 12:45 UTC, Ectalite commented
It should be good now

2020-10-14 11:11 UTC, 73VW approved these changes

2020-10-14 11:11 UTC, merged

2020-10-14 11:12 UTC, 73VW commented
Merci pour ton boulot c'est top!